# Generated by Django 3.2.4 on 2021-07-12 21:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Condominium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time when the object was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date time when the object was last modified.', verbose_name='modified at')),
                ('name_condominium', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time when the object was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date time when the object was last modified.', verbose_name='modified at')),
                ('department_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)])),
                ('department_block', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)])),
                ('number_habitants', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('department_owner', models.CharField(blank=True, max_length=200)),
                ('condominium_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='gestion_condominios.condominium')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileHabitant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time when the object was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date time when the object was last modified.', verbose_name='modified at')),
                ('p_number', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '999999999'. From 9 up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('p_number_emergency', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '999999999'. From 9 up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('department_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='department_id_owner', to='gestion_condominios.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PriorityOrUpgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time when the object was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date time when the object was last modified.', verbose_name='modified at')),
                ('name', models.CharField(max_length=200)),
                ('detail', models.TextField()),
                ('priority', models.BooleanField(default=False)),
                ('upgrade', models.BooleanField(default=False)),
                ('to_do', models.BooleanField(default=True)),
                ('doing', models.BooleanField(default=False)),
                ('done', models.BooleanField(default=False)),
                ('condominium_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condominium_data', to='gestion_condominios.condominium')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FinancialStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time when the object was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date time when the object was last modified.', verbose_name='modified at')),
                ('type_detail', models.CharField(max_length=100)),
                ('income', models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('expenses', models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('details', models.TextField()),
                ('condominium_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_status', to='gestion_condominios.condominium')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time when the object was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date time when the object was last modified.', verbose_name='modified at')),
                ('owner_department', models.CharField(max_length=100)),
                ('comment_title', models.CharField(blank=True, max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('flaw_title', models.CharField(blank=True, max_length=100)),
                ('flaw', models.TextField(blank=True)),
                ('condominium_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condominium_suggestions', to='gestion_condominios.condominium')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
